### ISSUE TITLE
Can i use this plugin on my Half-Life servers?

### ISSUE THREAD

**Issue by Mehmet-I** [milutinke/Ultimate-Anti-Cheat-UAC#1]
Hello, i hope you have good health.

I have a question. I have several Half-Life servers, and i'm tired of cheaters.
Do i have a chance to use this plugin on my servers?

Plugin shows this error. Do we have a chance to port to Half-Life?

[ 59] unknown                 unknown     unknown           ByM_UltimateAnt  bad load
[ 60] ReChecker Logging       freesrv     custom            ReCheckerLogger  running
( 59) Load fails: Module/Library "cstrike" required for plugin.  Check modules.ini.
60 plugins, 59 running

Thank you for your interest.

**Comment by milutinke** [comment]
Hello, the Anti Cheat is for Counter-Strike 1.6 and Counter-Strike: Condition Zero series.
I do not know how difficult it would be porting it to Half-Life since I have never scripted anything for it, you would have to remove cstrike module and lines which contain Counter-Strike weapons (Lines: 16, 1155, and 1231).
You also cant not use Re modules, WH Blocker, and ReCheckerLogger plugin, and you would have to write your own values in the configuration since the recoil works differently in Half-Life.
I think you are better off asking for a different anti-cheat on [https://forums.alliedmods.net/](https://forums.alliedmods.net/)

**Comment by Mehmet-I** [comment]
I will try. Thank you.

**Comment by mehmetilkay** [comment]
Bro, i deleted the lines, but I cannot compile sma.


//// ByM_UltimateAntiCheatEditledigim.sma
//
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(19) : error 021: symbol already defined: "set_dhudmessage"
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(24) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(34) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(37) : error 021: symbol already defined: "show_dhudmessage"
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(42) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(44) : warning 218: old style prototypes used with optional semicolumns
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(45) : error 054: unmatched closing brace
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(46) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(49) : warning 218: old style prototypes used with optional semicolumns
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(50) : error 054: unmatched closing brace
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(51) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(54) : error 021: symbol already defined: "get_players"
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(56) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(58) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(63) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(65) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(67) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(70) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(79) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(82) : warning 218: old style prototypes used with optional semicolumns
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(83) : error 054: unmatched closing brace
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(84) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(86) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(90) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(95) : error 021: symbol already defined: "vformat"
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(96) : warning 218: old style prototypes used with optional semicolumns
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(97) : error 054: unmatched closing brace
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(100) : error 021: symbol already defined: "ArrayDestroy"
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(103) : error 010: invalid function or declaration
// C:\Users\MonsterPc\Desktop\Re-Half-Life Server v10\valve\addons\amxmodx\scripting\include\dhudmessage.inc(106) : error 025: function heading differs from prototype
//
// Compilation aborted.
// 26 Errors.
// Could not locate output file compiled\ByM_UltimateAntiCheatEditledigim.amx (compile failed).
