### ISSUE TITLE
Error bullets and sound

### ISSUE THREAD

**Issue by cgi4eva** [milutinke/Ultimate-Anti-Cheat-UAC#2]
The sound of the glock and the famas are not right, from the glock the shot comes out as if it were firing a primary weapon and because of the famas the bullets are not shown

**Comment by milutinke** [comment]
That is ReHLDS Problem, Install ReGameDLL and it will be fixed

**Comment by cgi4eva** [comment]
When I put the problem to you it was updated, I had to uninstall the plugin until I got the solution.
